import "./pages/edit";
import "./pages/home";
import "./pages/info";
import "./pages/login";
import "./pages/menu";
import "./pages/my-data";
import "./pages/my-reports";
import "./pages/report-pet";
import "./pages/edit";
import "./pages/password";
import "./pages/lost-pets";
import "./pages/report-pet";
import "./pages/signup";
// import "./pages/prueba";
// import "./pages/dropzone";
import "./router";
import "./components/a";
import "./components/button";
import "./components/card";
import "./components/header";
import "./components/input";
import "./components/link";
import "./components/text";
import "./components/info-item";